###
GET http://localhost:3000/movies

###
POST http://localhost:3000/movies
Content-Type: application/json

{
    "directorId":27,
    "movieName":"Ek villan",
    "leadActor":"Gorilla"
}
###
GET http://localhost:3000/movies/46/
###
PUT http://localhost:3000/movies/47/
Content-Type: application/json

{
  "directorId": "24",
  "movieName": "Thor",
  "leadActor": "Christopher Hemsworth"
}
###
DELETE http://localhost:3000/movies/124/
###
GET http://localhost:3000/directors
###
GET http://localhost:3000/directors/27/movies/